#!/usr/bin/env node
// Write an AGENTS.md into a project, so the gates reach agents that are not
// Claude Code.
//
//   npx @alokraj68/craftkit agents            write ./AGENTS.md
//   npx @alokraj68/craftkit agents --print    print it, write nothing
//   npx @alokraj68/craftkit agents --cursor   also write .cursor/rules/craftkit.mdc
//
// AGENTS.md is the convention Codex, Cursor, opencode, Copilot and others read.
// The CLIs never needed a harness: they are npm packages that exit non-zero.
// What a harness adds is the judgement half, and that is Markdown, so it
// travels anywhere something will read a file.
import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

const TOOLS = [
  {
    pkg: '@alokraj68/plainspoken',
    bin: 'plainspoken',
    skill: 'plain-writing',
    does: 'fails the build when prose reads as machine-written',
    run: 'npx @alokraj68/plainspoken docs/ README.md',
    when: 'before committing any prose a human will read: docs, READMEs, release notes, UI copy, commit bodies',
  },
  {
    pkg: '@alokraj68/pagecheck',
    bin: 'pagecheck',
    skill: 'page-audit',
    does: 'finds horizontal overflow, text under 12px, tap targets under 44px and contrast below WCAG AA',
    run: 'npx @alokraj68/pagecheck ./dist',
    when: 'after any change to layout, spacing, type or colour, and before calling a UI change done',
  },
  {
    pkg: '@alokraj68/ats-resume',
    bin: 'ats-resume',
    skill: 'tailor-resume',
    does: 'checks an applicant tracking system can parse a résumé, and matches it against a posting',
    run: 'npx @alokraj68/ats-resume lint resume.json',
    when: 'when editing a CV or tailoring it to a job description',
  },
];

export function renderAgentsMd() {
  const rows = TOOLS.map((t) =>
    `| \`${t.bin}\` | ${t.does} | \`${t.run}\` |`).join('\n');

  const detail = TOOLS.map((t) => `### ${t.bin}

${t.does[0].toUpperCase()}${t.does.slice(1)}.

\`\`\`bash
${t.run}
\`\`\`

**Use it** ${t.when}.

The judgement half lives in \`node_modules/${t.pkg}/skills/${t.skill}/SKILL.md\`.
Read it before rewriting anything the linter flags: the fix is almost never a
synonym.`).join('\n\n');

  return `# AGENTS.md

Instructions for AI coding agents working in this repository. Written for the
AGENTS.md convention, so Codex, Cursor, opencode, Copilot, Gemini CLI, Claude
Code and anything else that reads a file can use it.

## Quality gates

These are npm packages, not harness plugins. They exit non-zero when they fail,
so they work the same from a terminal, from CI, or from inside an agent.

| Tool | Catches | Run |
|---|---|---|
${rows}

${detail}

## Before you say something is done

Taken from \`craft-setup\`. Claiming work is finished without running it is the
failure these rules exist to stop.

- Run the typecheck. Zero errors.
- Run the linter on every file you touched. Zero errors **and** zero warnings.
  If you touched a file you own its lint state, pre-existing problems included.
- Run the build once, at the end. Lint and typecheck do not catch template or
  markup errors; only the build does.
- Behaviour that can be checked, check it. Render it, hit the endpoint, run the
  test.
- If you could not run something, **say so plainly and name what is
  unverified.** Never imply otherwise.

"It compiles" is not "it works". If a check failed, say it failed and show the
output. A green summary over a red test is the one unrecoverable mistake,
because it destroys the reason anyone was reading the summary.

## Never commit unless asked

Do not run \`git commit\` or \`git push\` until the user has confirmed the change
**in that message**. A prior "yes, do X" does not carry forward to "and commit
it too". Finish the edit, show the diff and the verification output, and wait.

## Never invent a fact

Not a metric, a date, a client name, or an API that might exist. If a claim
cannot be verified, mark it unverified and ask. A confident sentence built on a
fabricated number is worse than an honest gap.

## Enforce in code, not in prose

If a rule can be machine-checked it belongs in something that fails the build,
not a checklist someone is trusted to follow. Never weaken a gate to make a run
pass: a red check means something broke, so fix the input.

---

Generated by [craftkit](https://github.com/alokraj68/craftkit). Regenerate with
\`npx @alokraj68/craftkit agents\`.
`;
}

export function renderCursorRule() {
  return `---
description: Quality gates from craftkit
alwaysApply: true
---

${renderAgentsMd().split('\n').slice(2).join('\n')}`;
}

export function writeAgents({ dir = process.cwd(), cursor = false, log = console.log } = {}) {
  const written = [];
  const target = join(dir, 'AGENTS.md');
  if (existsSync(target)) {
    // Someone else's AGENTS.md is not ours to overwrite.
    const body = readFileSync(target, 'utf8');
    if (!body.includes('Generated by [craftkit]')) {
      log(`  AGENTS.md already exists and was not written by craftkit.`);
      log(`  Left alone. Merge by hand, or see: npx @alokraj68/craftkit agents --print`);
      return written;
    }
  }
  writeFileSync(target, renderAgentsMd());
  written.push(target);
  if (cursor) {
    const dest = join(dir, '.cursor', 'rules');
    mkdirSync(dest, { recursive: true });
    const f = join(dest, 'craftkit.mdc');
    writeFileSync(f, renderCursorRule());
    written.push(f);
  }
  return written;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const args = process.argv.slice(2);
  if (args.includes('--print')) {
    process.stdout.write(renderAgentsMd());
  } else {
    const written = writeAgents({ cursor: args.includes('--cursor') });
    for (const w of written) console.log('wrote', w.replace(process.cwd(), '.'));
    if (!written.length) process.exit(1);
  }
}
